export default [
    {
      "id": 552,
      "user_id": 127,
      "user_name": "Meg Hughes",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/147_original.?1477415969",
      "user_short_blurb": "A writer of dark and strange stories.",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/552_original.jpg?1481095069",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/552_original.mp4?1481095069",
      "public_url": "https://api.letsyam.com/answers/b42aa2a7ca",
      "question": {
        "id": 1822,
        "content": "How much say/control will a screenwriter still have once you pass your script to the director/producer?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 84,
        "author_name": "Michael Cho",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/127_original.jpeg?1475833309",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/127_thumb.jpeg?1475833309",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/90ab84013a",
        "created_at": 1481093179,
        "question_cost": 1
      },
      "is_featured": true,
      "view_count": 18,
      "like_count": 2,
      "comment_count": 0,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1481095069,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 119.8
    },
    {
      "id": 547,
      "user_id": 614,
      "user_name": "David Sireika",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/693_original.?1480193650",
      "user_short_blurb": "Failing YouTuber, Professional Pessimist and Pornography Connoisseur",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/547_original.jpg?1481078916",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/547_original.mp4?1481078916",
      "public_url": "https://api.letsyam.com/answers/4cec6d055f",
      "question": {
        "id": 1773,
        "content": "What's it like to live on a boat?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 331,
        "author_name": "Tom Littrell",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_original.?1479164612",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_thumb.?1479164612",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/db921fa667",
        "created_at": 1480950639,
        "question_cost": 0
      },
      "is_featured": true,
      "view_count": 37,
      "like_count": 6,
      "comment_count": 0,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1481078916,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 60.4
    },
    {
      "id": 545,
      "user_id": 338,
      "user_name": "Alice Hattie",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/386_original.jpeg?1479170401",
      "user_short_blurb": "Inked Ex Pro Dom. Multipotentialite. Currently pulling what's left of my hair out due to finales.",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/545_original.jpg?1481043339",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/545_original.mp4?1481043339",
      "public_url": "https://api.letsyam.com/answers/0d45debcce",
      "question": {
        "id": 1751,
        "content": "Hello! My question is do you think there's a difference in gender roles? And why did you choose it?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 654,
        "author_name": "Samar Odeh",
        "author_avatar_url": "",
        "author_avatar_thumb_url": "",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/f165e5aa7e",
        "created_at": 1480864966,
        "question_cost": 0
      },
      "is_featured": true,
      "view_count": 30,
      "like_count": 4,
      "comment_count": 2,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1481043339,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 113.13
    },
    {
      "id": 544,
      "user_id": 549,
      "user_name": "Jacob Reitzin",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/613_original.jpeg?1479599783",
      "user_short_blurb": "Tech dude. created an app that connects dudes with trucks to people who need help moving their stuff",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/544_original.jpg?1481043267",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/544_original.mp4?1481043267",
      "public_url": "https://api.letsyam.com/answers/9262bc4f5e",
      "question": {
        "id": 1592,
        "content": "Can you tell us a bit about your app and how you came up with the idea for it?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 112,
        "author_name": "Alex Simon",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/143_original.jpeg?1476930667",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/143_thumb.jpeg?1476930667",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/317b91dee4",
        "created_at": 1480492177,
        "question_cost": 1
      },
      "is_featured": true,
      "view_count": 20,
      "like_count": 3,
      "comment_count": 0,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1481043267,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 119.97
    },
    {
      "id": 538,
      "user_id": 621,
      "user_name": "Kat ",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/703_original.?1480317983",
      "user_short_blurb": "I am a writer, geek, gamer, makeup rookie and I co-host the Two Geeks in Gotham podcast!",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/538_original.jpg?1481005546",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/538_original.mp4?1481005546",
      "public_url": "https://api.letsyam.com/answers/d935b63aea",
      "question": {
        "id": 1550,
        "content": "If someone were stubborn about mental illness being non-legitimate, how would you go about reducing its stigma and circumventing ignorance?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 331,
        "author_name": "Tom Littrell",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_original.?1479164612",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_thumb.?1479164612",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/6dfde07f9f",
        "created_at": 1480404277,
        "question_cost": 1
      },
      "is_featured": true,
      "view_count": 51,
      "like_count": 4,
      "comment_count": 0,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1481005546,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 114.97
    },
    {
      "id": 533,
      "user_id": 564,
      "user_name": "Kevin Littrell",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/629_original.jpg?1479672708",
      "user_short_blurb": "Artist ° Explorer 🕉",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/533_original.jpg?1481001295",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/533_original.mp4?1481001295",
      "public_url": "https://api.letsyam.com/answers/93cbb597b5",
      "question": {
        "id": 1697,
        "content": "What's it like being the middle brother of 3?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 331,
        "author_name": "Tom Littrell",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_original.?1479164612",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_thumb.?1479164612",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/900c1423cd",
        "created_at": 1480733768,
        "question_cost": 1
      },
      "is_featured": true,
      "view_count": 38,
      "like_count": 3,
      "comment_count": 1,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1481001295,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 62.93
    },
    {
      "id": 532,
      "user_id": 565,
      "user_name": "Ann Gustafson",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/631_original.jpeg?1479695545",
      "user_short_blurb": "Expert on wit and charm.Aspiring Polyglot Interpreter.I sew my all my clothes.",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/532_original.jpg?1480980955",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/532_original.mp4?1480980955",
      "public_url": "https://api.letsyam.com/answers/a0b2622f99",
      "question": {
        "id": 1652,
        "content": "Do you see a problem with \"tolerating\" other people? Tolerance to me assumes you are right and therefore hold power over the people being tolerated.",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 331,
        "author_name": "Tom Littrell",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_original.?1479164612",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_thumb.?1479164612",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/e9dd244b8e",
        "created_at": 1480666188,
        "question_cost": 1
      },
      "is_featured": true,
      "view_count": 64,
      "like_count": 4,
      "comment_count": 2,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1480980955,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 109.9
    },
    {
      "id": 529,
      "user_id": 589,
      "user_name": "Anna Ryan",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/657_original.jpeg?1479856093",
      "user_short_blurb": "Actor. Traveler. Granddaughter of Alzheimer's. Earth conscious. Culture curious🌎☀️✨🇬🇧🇺🇸",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/529_original.jpg?1480925360",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/529_original.mp4?1480925360",
      "public_url": "https://api.letsyam.com/answers/ac86773eb4",
      "question": {
        "id": 1730,
        "content": "How did your granny first discover that she might have Alzheimer's?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 84,
        "author_name": "Michael Cho",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/127_original.jpeg?1475833309",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/127_thumb.jpeg?1475833309",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/b495122952",
        "created_at": 1480757633,
        "question_cost": 0
      },
      "is_featured": true,
      "view_count": 38,
      "like_count": 2,
      "comment_count": 2,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1480925360,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 119.97
    },
    {
      "id": 519,
      "user_id": 637,
      "user_name": "Arjun Patel",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/727_original.?1480464115",
      "user_short_blurb": "Besides being obsessed with growth hacking - I love meditation and reading.",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/519_original.jpg?1480910889",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/519_original.mp4?1480910889",
      "public_url": "https://api.letsyam.com/answers/7733b56dc2",
      "question": {
        "id": 1707,
        "content": "How do you focus on a clear mind when meditating? How do you dismiss thoughts?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 331,
        "author_name": "Tom Littrell",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_original.?1479164612",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/372_thumb.?1479164612",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/e948616c24",
        "created_at": 1480736026,
        "question_cost": 1
      },
      "is_featured": true,
      "view_count": 17,
      "like_count": 2,
      "comment_count": 0,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1480910889,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 31.33
    },
    {
      "id": 513,
      "user_id": 207,
      "user_name": "Katie Elster",
      "user_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/240_original.jpg?1478585463",
      "user_short_blurb": "Screenwriter, Actor, Dancer. Cinema and Photography. Los Angeles.",
      "image_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/images/513_original.jpg?1480896811",
      "video_url": "https://d2g9p8cekugjwh.cloudfront.net/answers/videos/513_original.mp4?1480896811",
      "public_url": "https://api.letsyam.com/answers/ce82a65522",
      "question": {
        "id": 1757,
        "content": "What type of movies do you like to write?",
        "is_answered": true,
        "answer_count": 2,
        "author_id": 207,
        "author_name": "Katie Elster",
        "author_avatar_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/240_original.jpg?1478585463",
        "author_avatar_thumb_url": "https://d2g9p8cekugjwh.cloudfront.net/attachments/images/240_thumb.jpg?1478585463",
        "is_anonymous": false,
        "vote_count": 0,
        "has_voted": false,
        "public_url": "https://api.letsyam.com/questions/50cf229711",
        "created_at": 1480896680,
        "question_cost": 0
      },
      "is_featured": true,
      "view_count": 23,
      "like_count": 5,
      "comment_count": 1,
      "has_liked": false,
      "ask_for_bio": false,
      "user_group_bio": null,
      "group": null,
      "created_at": 1480896812,
      "is_trending": false,
      "has_paid": false,
      "is_system_answer": false,
      "question_cost": 0,
      "video_duration": 110.4
    }
  ]
  
